apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: yyf24br4o-java-springboot
  janus-idp.io/tekton: yyf24br4o-java-springboot
  backstage.io/kubernetes-id: yyf24br4o-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: yyf24br4o-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
